# Generated by Django 3.0.8 on 2020-08-01 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(max_length=200)),
                ('product_price', models.FloatField(max_length=10)),
                ('product_qentity', models.TextField(max_length=200)),
                ('product_shortD', models.TextField(max_length=300)),
                ('product_longD', models.TextField()),
                ('product_img', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=200, unique=True)),
                ('password', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qentity', models.IntegerField()),
                ('state', models.IntegerField(max_length=3)),
                ('product_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qentity', models.IntegerField()),
                ('state', models.IntegerField(max_length=3)),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
        ),
    ]
