# Generated by Django 3.0.8 on 2020-08-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='state',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=200),
        ),
    ]
