# Generated by Django 3.0.8 on 2020-08-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200801_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(default=1),
        ),
    ]
