# Generated by Django 3.0.8 on 2020-08-02 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200802_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='user',
            name='order',
        ),
        migrations.AddField(
            model_name='cart',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.TextField(default='a', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.TextField(default='a', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
