# Generated by Django 3.0.8 on 2020-08-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200802_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_qentity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_qentity',
            field=models.IntegerField(default=1),
        ),
    ]
