# Generated by Django 3.0.8 on 2020-08-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200814_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='myProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
            ],
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='pic_folder/star.png', upload_to='pic_folder/'),
        ),
    ]
