# Generated by Django 3.0.8 on 2020-08-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200814_0655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myProduct',
        ),
    ]
