# Generated by Django 3.0.8 on 2020-08-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_delete_myproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='polls/static/pic_folder/star.png', upload_to='polls/static/pic_folder/'),
        ),
    ]
