# Generated by Django 3.0.8 on 2020-08-15 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20200814_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.TextField(max_length=200, null=True)),
                ('buyer', models.TextField(max_length=200, null=True)),
                ('product', models.TextField(max_length=700, null=True)),
                ('state', models.IntegerField()),
                ('product_qentity', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Cart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='buyer',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AddField(
            model_name='user',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Order'),
            preserve_default=False,
        ),
    ]
