# Generated by Django 3.0.8 on 2020-08-18 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20200815_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.TextField(max_length=400)),
                ('state', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='SubSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsort', models.TextField(max_length=400)),
                ('state', models.IntegerField(default=1)),
                ('sort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Sort')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Sort'),
        ),
        migrations.AddField(
            model_name='product',
            name='subsort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.SubSort'),
        ),
    ]
