# Generated by Django 3.0.8 on 2020-08-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20200818_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_qentity',
            field=models.IntegerField(default=1),
        ),
    ]
