# Generated by Django 3.0.8 on 2020-08-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20200818_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
