# Generated by Django 3.0.8 on 2020-08-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20200818_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.TextField(max_length=200),
        ),
    ]
